/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_wxj_jni_demo_JniDemo */

#ifndef _Included_com_wxj_jni_demo_JniDemo
#define _Included_com_wxj_jni_demo_JniDemo
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_wxj_jni_demo_JniDemo
 * Method:    printf
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_wxj_jni_demo_JniDemo_printf
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
